# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Fristpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FristPage(object):
    def setupUi(self, FristPage):
        FristPage.setObjectName("FristPage")
        FristPage.resize(799, 461)
        self.label = QtWidgets.QLabel(FristPage)
        self.label.setGeometry(QtCore.QRect(250, 100, 291, 101))
        font = QtGui.QFont()
        font.setFamily("Itim")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.StrBut = QtWidgets.QPushButton(FristPage)
        self.StrBut.setEnabled(True)
        self.StrBut.setGeometry(QtCore.QRect(280, 250, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.StrBut.setFont(font)
        self.StrBut.setStyleSheet("QPushButton{\n"
                                  "background-color: #ddd;\n"
                                  "border: none;\n"
                                  "color: black;\n"
                                  "padding: 16px 32px;\n"
                                  "text-align: center;\n"
                                  "font-size: 16px;\n"
                                  "margin: 4px 2px;\n"
                                  "transition: 0.3s;\n"
                                  "}\n"
                                  "QPushButton:hover{\n"
                                  "transition-delay:3s;\n"
                                  "background-color:#4CAF50;\n"
                                  "color: rgb(255, 255, 255);\n"
                                  "}")
        self.StrBut.setObjectName("StrBut")
        self.StrBut.clicked.connect(self.change)
        self.retranslateUi(FristPage)
        QtCore.QMetaObject.connectSlotsByName(FristPage)
        self.thiswindow = FristPage

    def change(self):
        from MainMeni import Ui_MainWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.thiswindow.hide()

    def retranslateUi(self, FristPage):
        _translate = QtCore.QCoreApplication.translate
        FristPage.setWindowTitle(_translate("FristPage", "Frist"))
        self.label.setText(_translate("FristPage", "Vacation Places"))
        self.StrBut.setText(_translate("FristPage", "Start"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    FristPage = QtWidgets.QWidget()
    ui = Ui_FristPage()
    ui.setupUi(FristPage)
    FristPage.show()
    sys.exit(app.exec_())
