# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainMeni.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 461)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 70, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Itim")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 70, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Itim")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(550, 70, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Itim")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(160, 240, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Itim")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(360, 240, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Itim")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(550, 240, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Itim")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(250, 20, 300, 41))
        font = QtGui.QFont()
        font.setFamily("Itim")
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.butNorthern = QtWidgets.QPushButton(self.centralwidget)
        self.butNorthern.setGeometry(QtCore.QRect(130, 110, 171, 131))
        self.butNorthern.setStyleSheet("QPushButton{background-color\n"
                                       " :  Transparent;\n"
                                       "background-image:url(\'./picture/north.png\') 171px 131px no-repeat\n"
                                       "scroll 0 0 transparent;\n"
                                       "border: none;\n"
                                       "    cursor:pointer;\n"
                                       "    overflow: hidden;\n"
                                       "    outline:none;\n"
                                       "}")
        self.butNorthern.setText("")
        self.butNorthern.setObjectName("butNorthern")
        self.butCentral = QtWidgets.QPushButton(self.centralwidget)
        self.butCentral.setGeometry(QtCore.QRect(320, 110, 171, 131))
        self.butCentral.setStyleSheet("QPushButton{background-color\n"
                                      " :  Transparent;\n"
                                      "background-image:url(\'./picture/central.png\') 171px 131px no-repeat\n"
                                      "scroll 0 0 transparent;\n"
                                      "border: none;\n"
                                      "    cursor:pointer;\n"
                                      "    overflow: hidden;\n"
                                      "    outline:none;\n"
                                      "}")
        self.butCentral.setText("")
        self.butCentral.setObjectName("butCentral")
        self.butEastern = QtWidgets.QPushButton(self.centralwidget)
        self.butEastern.setGeometry(QtCore.QRect(510, 110, 171, 131))
        self.butEastern.setStyleSheet("QPushButton{background-color\n"
                                      " :  Transparent;\n"
                                      "background-image:url(\'./picture/eastern.png\') 171px 131px no-repeat\n"
                                      "scroll 0 0 transparent;\n"
                                      "border: none;\n"
                                      "    cursor:pointer;\n"
                                      "    overflow: hidden;\n"
                                      "    outline:none;\n"
                                      "}")
        self.butEastern.setText("")
        self.butEastern.setObjectName("butEastern")
        self.butNortheast = QtWidgets.QPushButton(self.centralwidget)
        self.butNortheast.setGeometry(QtCore.QRect(130, 280, 171, 131))
        self.butNortheast.setStyleSheet("QPushButton{background-color\n"
                                        " :  Transparent;\n"
                                        "background-image:url(\'./picture/northeast.png\') 171px 131px no-repeat\n"
                                        "scroll 0 0 transparent;\n"
                                        "border: none;\n"
                                        "    cursor:pointer;\n"
                                        "    overflow: hidden;\n"
                                        "    outline:none;\n"
                                        "}")
        self.butNortheast.setText("")
        self.butNortheast.setObjectName("butNortheast")
        self.butWestern = QtWidgets.QPushButton(self.centralwidget)
        self.butWestern.setGeometry(QtCore.QRect(320, 280, 171, 131))
        self.butWestern.setStyleSheet("QPushButton{background-color\n"
                                      " :  Transparent;\n"
                                      "background-image:url(\'./picture/western.png\') 171px 131px no-repeat\n"
                                      "scroll 0 0 transparent;\n"
                                      "border: none;\n"
                                      "    cursor:pointer;\n"
                                      "    overflow: hidden;\n"
                                      "    outline:none;\n"
                                      "}")
        self.butWestern.setText("")
        self.butWestern.setObjectName("butWestern")
        self.butSouthern = QtWidgets.QPushButton(self.centralwidget)
        self.butSouthern.setGeometry(QtCore.QRect(510, 280, 171, 131))
        self.butSouthern.setStyleSheet("QPushButton{background-color\n"
                                       " :  Transparent;\n"
                                       "background-image:url(\'./picture/south.png\') 171px 131px no-repeat\n"
                                       "scroll 0 0 transparent;\n"
                                       "border: none;\n"
                                       "    cursor:pointer;\n"
                                       "    overflow: hidden;\n"
                                       "    outline:none;\n"
                                       "}")
        self.butSouthern.setText("")
        self.butSouthern.setObjectName("butSouthern")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.butNorthern.clicked.connect(lambda: self.Gotoselect("ภาคเหนือ"))
        self.butCentral.clicked.connect(lambda: self.Gotoselect("ภาคกลาง"))
        self.butEastern.clicked.connect(lambda: self.Gotoselect("ภาคตะวันออก"))
        self.butNortheast.clicked.connect(lambda: self.Gotoselect("ภาคตะวันออกเฉียงเหนือ"))
        self.butWestern.clicked.connect(lambda: self.Gotoselect("ภาคตะวันตก"))
        self.butSouthern.clicked.connect(lambda: self.Gotoselect("ภาคใต้"))
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.thiswindow = MainWindow

    def Gotoselect(self, tern):
        from selectdata import Ui_selectdatapage
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_selectdatapage()
        self.ui.setupUi(self.window)
        self.ui.settext(tern)
        self.ui.setcmbProvince(tern)
        self.ui.display(tern)
        self.window.show()
        self.thiswindow.hide()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ภาคเหนือ"))
        self.label_2.setText(_translate("MainWindow", "ภาคกลาง"))
        self.label_3.setText(_translate("MainWindow", "ภาคตะวันออก"))
        self.label_4.setText(_translate("MainWindow", "ภาคตะวันออกเฉียงเหนือ"))
        self.label_5.setText(_translate("MainWindow", "ภาคตะวันตก"))
        self.label_6.setText(_translate("MainWindow", "ภาคใต้"))
        self.label_7.setText(_translate("MainWindow","เลือกภาคที่ต้องการ"))



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
